name: CI

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Started
      run: echo Change
    - name: Build and Push to Github Registry
      uses: mr-smithers-excellent/docker-build-push@v3.1
      with:
        # Name of the Docker image
        image: wppscrapper
        # Tag override for Docker image
        tag: v0.0.1
        # Target Docker registry
        registry: docker.pkg.github.com/ribeiroferreiralucas/wppscrapper
        # Location of Dockerfile, if not Dockerfile in root directory
        username: ribeiroferreiralucas
        # Password for Docker registry
        password: ${{ secrets.docker_token }}